baseURL = "https://deti.ochrance.cz/"
defaultContentLanguage = "cs"
title = "Dětský ombudsman — ochránce práv dětí"

[outputs]
home = ["HTML", "RSS", "htaccess"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.htaccess]
baseName = ""
isPlainText = true
mediaType = "text/htaccess"

[mediaTypes]
[mediaTypes."text/htaccess"]
suffixes = ["htaccess"]
